name: wisata_candi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/borobudur.jpeg
    - images/jago.jpeg
    - images/kalasan.jpeg
    - images/logo_candi.png
    - images/lumbung.jpeg
    - images/mendut.jpeg
    - images/placeholder_image.png
    - images/plaosan.jpeg
    - images/prambanan.jpeg
    - images/sari.jpeg
    - images/sewu.jpeg